#!/usr/bin/env bash
# Import GraphPop CSVs into Neo4j using neo4j-admin database import full.
#
# Usage:
#   sudo bash scripts/neo4j-import.sh [CSV_DIR] [DATABASE]
#
# Defaults:
#   CSV_DIR  = data/raw/1000g/csv_out
#   DATABASE = graphpop
#
# Prerequisites:
#   - Neo4j must be STOPPED before running this script
#   - CSVs must have been generated by CSVEmitter.run()
#   - Run as root (or the neo4j user) so neo4j-admin can write to the data dir
set -euo pipefail

CSV_DIR="${1:-data/raw/1000g/csv_out}"
DATABASE="${2:-graphpop}"

# Resolve to absolute path
CSV_DIR="$(cd "$CSV_DIR" && pwd)"

echo "==> GraphPop Neo4j Import"
echo "    CSV directory : $CSV_DIR"
echo "    Database      : $DATABASE"
echo ""

# ---------------------------------------------------------------------------
# Validate inputs
# ---------------------------------------------------------------------------

REQUIRED_FILES=(
    variant_nodes.csv
    sample_nodes.csv
    population_nodes.csv
    chromosome_nodes.csv
    carries_edges.csv
    next_edges.csv
    on_chromosome_edges.csv
    in_population_edges.csv
)

for f in "${REQUIRED_FILES[@]}"; do
    if [[ ! -f "$CSV_DIR/$f" ]]; then
        echo "ERROR: Missing required file: $CSV_DIR/$f" >&2
        exit 1
    fi
done
echo "==> All 8 CSV files found"

# Print file sizes for reference
echo ""
echo "    File sizes:"
ls -lh "$CSV_DIR"/*.csv | awk '{printf "    %-35s %s\n", $NF, $5}'
echo ""

# ---------------------------------------------------------------------------
# Stop Neo4j if running
# ---------------------------------------------------------------------------

if neo4j status >/dev/null 2>&1; then
    echo "==> Stopping Neo4j..."
    neo4j stop
    sleep 2
fi

# ---------------------------------------------------------------------------
# Run neo4j-admin database import full
# ---------------------------------------------------------------------------

echo "==> Starting neo4j-admin database import full..."
echo ""

neo4j-admin database import full \
    --overwrite-destination=true \
    --array-delimiter=";" \
    --id-type=string \
    --skip-bad-relationships=true \
    --skip-duplicate-nodes=true \
    --bad-tolerance=1000 \
    --threads="$(nproc)" \
    --high-parallel-io=on \
    --nodes=Variant="$CSV_DIR/variant_nodes.csv" \
    --nodes=Sample="$CSV_DIR/sample_nodes.csv" \
    --nodes=Population="$CSV_DIR/population_nodes.csv" \
    --nodes=Chromosome="$CSV_DIR/chromosome_nodes.csv" \
    --relationships=CARRIES="$CSV_DIR/carries_edges.csv" \
    --relationships=NEXT="$CSV_DIR/next_edges.csv" \
    --relationships=ON_CHROMOSOME="$CSV_DIR/on_chromosome_edges.csv" \
    --relationships=IN_POPULATION="$CSV_DIR/in_population_edges.csv" \
    --report-file="$CSV_DIR/import.report" \
    "$DATABASE"

echo ""
echo "==> Import complete."
echo "    Report: $CSV_DIR/import.report"
echo ""

# ---------------------------------------------------------------------------
# Post-import: create the database if needed, then create indexes
# ---------------------------------------------------------------------------

echo "==> Creating post-import indexes..."

# Write a Cypher script for indexes and constraints
INDEX_SCRIPT="$CSV_DIR/post_import_indexes.cypher"
cat > "$INDEX_SCRIPT" << 'CYPHER'
// Uniqueness constraints (also create indexes)
CREATE CONSTRAINT variant_id IF NOT EXISTS FOR (v:Variant) REQUIRE v.`variantId` IS UNIQUE;
CREATE CONSTRAINT sample_id IF NOT EXISTS FOR (s:Sample) REQUIRE s.`sampleId` IS UNIQUE;
CREATE CONSTRAINT population_id IF NOT EXISTS FOR (p:Population) REQUIRE p.`populationId` IS UNIQUE;
CREATE CONSTRAINT chromosome_id IF NOT EXISTS FOR (c:Chromosome) REQUIRE c.`chromosomeId` IS UNIQUE;

// Lookup indexes for common queries
CREATE INDEX variant_chr_pos IF NOT EXISTS FOR (v:Variant) ON (v.chr, v.`pos`);
CREATE INDEX variant_type IF NOT EXISTS FOR (v:Variant) ON (v.variant_type);
CREATE INDEX variant_af_total IF NOT EXISTS FOR (v:Variant) ON (v.af_total);
CYPHER

echo "    Index script written to: $INDEX_SCRIPT"
echo ""
echo "==> Next steps:"
echo "    1. Start Neo4j:        sudo neo4j start"
echo "    2. Create database:    CREATE DATABASE $DATABASE IF NOT EXISTS;"
echo "    3. Apply indexes:      cat $INDEX_SCRIPT | cypher-shell -d $DATABASE"
echo ""
echo "    Or run all at once:"
echo "      sudo neo4j start && sleep 5 && \\"
echo "        cypher-shell -d system \"CREATE DATABASE $DATABASE IF NOT EXISTS;\" && \\"
echo "        sleep 3 && \\"
echo "        cat $INDEX_SCRIPT | cypher-shell -d $DATABASE"
